name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_splunk_observability_cloud_aws_account_id: ${{ secrets.SPLUNK_OBSERVABILITY_CLOUD_ACCOUNT_ID }}
      TF_VAR_splunk_observability_cloud_aws_external_id: ${{ secrets.SPLUNK_OBSERVABILITY_CLOUD_EXTERNAL_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
